name: Build Wheels (abi3)

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cibw_arch: x86_64
          - os: macos-13
            cibw_arch: x86_64
          - os: macos-latest
            cibw_arch: arm64
          - os: windows-latest
            cibw_arch: AMD64

    env:
      CIBW_BUILD: "cp310-*"
      CIBW_SKIP: "*-win32 *-manylinux_i686"
      CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
      CIBW_ARCHS_MACOS: ${{ matrix.cibw_arch }}
      CIBW_ARCHS_WINDOWS: ${{ matrix.cibw_arch }}
      # 可选：manylinux 基线
      # CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
      # CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
      CIBW_TEST_COMMAND: "python -c \"import word2vec_matryoshka; print(getattr(word2vec_matryoshka, '__version__', 'ok'))\""

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build wheels (abi3)
        uses: pypa/cibuildwheel@v3.1.4
        with:
          package-dir: .

      - name: Setup Python for sdist
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Build sdist
        run: |
          python -m pip install --upgrade build
          python -m build --sdist .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.cibw_arch }}
          path: |
            wheelhouse/*.whl
            dist/*.tar.gz
