name: Build Wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            cibw_arch: x86_64
            cibw_platform: linux
          # Linux aarch64 (通过 QEMU，cibuildwheel自动处理)
          - os: ubuntu-latest
            cibw_arch: aarch64
            cibw_platform: linux
          # macOS x86_64 (Intel)
          - os: macos-13
            cibw_arch: x86_64
            cibw_platform: macos
          # macOS arm64 (Apple Silicon)
          - os: macos-latest
            cibw_arch: arm64
            cibw_platform: macos
          # Windows x86_64
          - os: windows-latest
            cibw_arch: x86_64
            cibw_platform: windows

    env:
      CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp314-*"
      CIBW_SKIP: "*-win32 *-manylinux_i686"
      CIBW_BEFORE_BUILD_LINUX: "curl -sSf https://sh.rustup.rs | sh -s -- -y"
      CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"
      CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
      CIBW_ARCHS_MACOS: ${{ matrix.cibw_arch }}
      CIBW_ARCHS_WINDOWS: ${{ matrix.cibw_arch }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.10+
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Build wheels via cibuildwheel
        uses: pypa/cibuildwheel@v2.19.1
        with:
          package-dir: .

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels-${{ matrix.os }}-${{ matrix.cibw_arch }}
          path: ./wheelhouse/*.whl
